from src.customer.schemas.post.bodys.cross_selling import CrossSelling
from .get import (
    SearchCustomersQueryParams,
    BlacklistQueryParams,
    CustomerQueryParamsSensor,
    SearchCustomersResponse,
    CustomerProfileHeaderResponse,
    CustomerProfileDetailResponse,
    CustomerLogBook,
    CustomerMarketingSubscriptions,
    SearchCustomers,
    CustomerNotesAndcomments,
    NotesAndCommentsResponse,
    BlacklistCustomersResponse,
    BlacklistCustomer,
    SensorHistoryResponse,
    SearchCrudQueryParams,
    SearchUpdate,
    SearchUpdateResponse,
    SensorHistoryResponse,
    SearchMerge,
    SearchMergeResponse,
    CrossSellingQueryParams,
    CrossSellingAndProductsResponse,
    CrossSelling,
    Product,
    Segmenter,
    SegmenterResponse,
    SegmenterQueryParams,
    AuthorsInSegments,
)

from .post import (
    BlackListBody,
    BlackListBodyResponse,
    CreateCustomerBody,
    CustomerCRUDResponse,
    UpdateCustomerBody,
    MergeCustomerBody,
    CrossSellingCreatedResponse,
    NewCrossSelling,
    CrossSelling,
    Product,
)
from .put import PutScoreCard
